### ISSUE TITLE
download.py connection timeout causes crash during dr-build

### ISSUE THREAD

**Issue by RevelBerry** [hearmeneigh/dataset-rising#2]
During dr-build, while images are downloading, a connection timeout to e621 can cause "ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fbf83d4dc90>, 'Connection to static1.e621.net timed out." which will break the dr-build, losing the existing dataset download progress.

This change to global_fetch will resolve this:
def global_fetch(url, agent: str) -> Optional[bytes]:
    try:
        r = requests.get(url, headers={
            'user-agent': agent
        }, allow_redirects=True)

        r.raise_for_status()  # Raise an exception for non-200 status codes
        return r.content
    except requests.exceptions.RequestException as e:
        print(f'Could not fetch {url}: {e}')
        return None

**Comment by hearmeneigh** [comment]
Thanks! Fixed in `1.0.4`
