### ISSUE TITLE
Database Write Times

### ISSUE THREAD

**Issue by KillaMeep** [hearmeneigh/dataset-rising#4]
Im not sure if this is actually an _issue_, but it seems like the longer I let the dr-import command run, the worse the write speed gets. I got about 3 hours in, and was getting about 18 tags/s. I stopped the import and restarted (hoping it saved progress and was just a bug), but it seems like the same thing is happening again. Any recommendations?

**Comment by KillaMeep** [comment]
Update, found out that maybe running dr-db-create would be a good idea haha. I think that you should add that into the main readme after the dr-db-up part, as it isnt mentioned anywhere other then in up.sh, which generally wont be used for the pip users.  I'll mark this as closed, but just an idea.

**Comment by hearmeneigh** [comment]
Agreed. That was the design, too, so there must be a bug somewhere.

**Comment by KillaMeep** [comment]
It was just user error. I didn't realize you had to use the dr-db-create as well dr-db-up. Once I did that it was all working. Im going to re-close this as its solved
